# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import requests
import geopandas as gpd

### More Chicagoans lacked heat in January than any month since 2019 amid historic cold

1. Go to the Chicago Data Portal: https://data.cityofchicago.org/
2. Find each dataset. Building violations, ward, and police.
3. Add a data notes section to your github readme. This should include information about the source of your data, where it came from, how often it is updated, and the period of data it contains (e.g. 2010-present or 2012 to 2019)
4. Lastly, test that this import works. This may take a while as the dataset is large.

In [2]:
build = pd.read_csv('https://data.cityofchicago.org/resource/22u3-xenr.csv?$limit=3000000')

In [3]:
# you can use any of these
ward = gpd.read_file('https://data.cityofchicago.org/api/geospatial/sp34-6z76?method=export&format=GeoJSON')
police = gpd.read_file('https://data.cityofchicago.org/api/geospatial/fthy-xz3r?method=export&format=GeoJSON')

###Testing that the imports work

In [4]:
#Testing that this import of the 'build' dataset works using .head()
build.head()

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,address,street_number,street_direction,street_name,street_type,property_group,ssa,latitude,longitude,location
0,7149869,2024-04-16T14:21:39.000,2024-04-16T00:00:00.000,CN138106,OPEN,NaN,STOP/REMOVE NUISANCE,OTHER : :OTHER,REAR YARD - LARGE OVERGROWN DEAD TREE.,Remove and stop nuisance. (7-28-060),...,10500 S LA SALLE ST,10500,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)"
1,7149868,2024-04-16T14:21:39.000,2024-04-16T00:00:00.000,CN067014,OPEN,NaN,REPAIR ROOF,OTHER : :OTHER,BUILDING / ROOF - ROTTING AND DETERIORATED SHI...,Failed to maintain roof in sound condition and...,...,10500 S LA SALLE ST,10500,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)"
2,7149866,2024-04-16T14:21:39.000,2024-04-16T00:00:00.000,CN104015,OPEN,NaN,"REPLCE WINDOW PANES, PLEXGLAS",OTHER : :OTHER,NORTH ELEVATION / 2ND FLOOR WINDOW - BROKEN G...,"Replace broken, missing or defective window pa...",...,10500 S LA SALLE ST,10500,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)"
3,7149865,2024-04-16T14:21:39.000,2024-04-16T00:00:00.000,CN079014,OPEN,NaN,REPAIR/REBUILD GARAGE OR SHED,OTHER : :OTHER,"WEST ELEVATION / 2 CAR FRAME GARAGE / ROOF, E...",Failed to maintain garage in sound condition a...,...,10500 S LA SALLE ST,10500,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)"
4,7149867,2024-04-16T14:21:39.000,2024-04-16T00:00:00.000,CN070024,OPEN,NaN,REPAIR PORCH SYSTEM,OTHER : :OTHER,EAST ELEVATION / 1 STORY WOOD PORCH WITH ROOF ...,Failed to repair or replace defective or missi...,...,10500 S LA SALLE ST,10500,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)"

In [5]:
#Testing that this import of the 'build' dataset works using .tail()
build.tail()

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,address,street_number,street_direction,street_name,street_type,property_group,ssa,latitude,longitude,location
1906796,1345600,2006-04-10T15:39:50.000,2006-01-01T00:00:00.000,CN192019,OPEN,NaN,"NOTIFY DOB, USE OF VACANT LND",NaN,BUILDING IS VACANT AND OPENED,Notify Building Dept of proposed use of vacant...,...,2256 W 47TH PL,2256,W,47TH,PL,323210,NaN,41.807634,-87.681915,"\n, \n(41.80763401160266, -87.6819153498679)"
1906797,1345598,2006-04-10T15:39:28.000,2006-01-01T00:00:00.000,CN196039,OPEN,NaN,POST OWNER INFO ON ABDN BLDG,NaN,NaN,"Post, on abandoned building, name, address and...",...,2256 W 47TH PL,2256,W,47TH,PL,323210,NaN,41.807634,-87.681915,"\n, \n(41.80763401160266, -87.6819153498679)"
1906798,1430846,2008-01-24T13:55:53.000,2006-01-01T00:00:00.000,CN107025,COMPLIED,2007-11-28T00:00:00.000,INSTALL EXIT SIGN,NaN,ALL CORRIDORS AND STAIRWELL EXIT SIGN OUT,Failed to install standard internally illumina...,...,6501 S LOWE AVE,6501,S,LOWE,AVE,19693,NaN,41.776074,-87.640625,"\n, \n(41.7760739361563, -87.64062455203374)"
1906799,1345212,2007-11-07T14:35:54.000,2006-01-01T00:00:00.000,CN073024,OPEN,NaN,REPAIR EXTERIOR DOOR FRAME,NaN,EAST EXTERIOR DOOR FRAME ROTTED,Failed to maintain exterior door frames to exc...,...,5108 S CALUMET AVE,5108,S,CALUMET,AVE,327758,52.0,41.801766,-87.617887,"\n, \n(41.80176555860429, -87.6178867686376)"
1906800,1345225,2007-07-31T14:59:14.000,2006-01-01T00:00:00.000,CN067014,OPEN,NaN,REPAIR ROOF,NaN,331 ROOF LEAKS,Failed to maintain roof in sound condition and...,...,5108 S CALUMET AVE,5108,S,CALUMET,AVE,327758,52.0,41.801766,-87.617887,"\n, \n(41.80176555860429, -87.6178867686376)"

In [6]:
#Testing that this import of the 'build' dataset works using .columns
build.columns

Index(['id', 'violation_last_modified_date', 'violation_date',
       'violation_code', 'violation_status', 'violation_status_date',
       'violation_description', 'violation_location',
       'violation_inspector_comments', 'violation_ordinance', 'inspector_id',
       'inspection_number', 'inspection_status', 'inspection_waived',
       'inspection_category', 'department_bureau', 'address', 'street_number',
       'street_direction', 'street_name', 'street_type', 'property_group',
       'ssa', 'latitude', 'longitude', 'location'],
      dtype='object')

In [7]:
#Testing that this import of the 'build' dataset works using .shape
build.shape

(1906801, 26)

In [8]:
#Testing that this import of the 'build' dataset works using .info()
build.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1906801 entries, 0 to 1906800
Data columns (total 26 columns):
 #   Column                        Dtype
---  ------                        -----
 0   id                            int64
 1   violation_last_modified_date  object
 2   violation_date                object
 3   violation_code                object
 4   violation_status              object
 5   violation_status_date         object
 6   violation_description         object
 7   violation_location            object
 8   violation_inspector_comments  object
 9   violation_ordinance           object
 10  inspector_id                  object
 11  inspection_number             int64
 12  inspection_status             object
 13  inspection_waived             object
 14  inspection_category           object
 15  department_bureau             object
 16  address                       object
 17  street_number                 int64
 18  street_direction              object
 19  street_name                   object
 20  street_type                   object
 21  property_group                int64
 22  ssa                           float64
 23  latitude                      float64
 24  longitude                     float64
 25  location                      object
dtypes: float64(3), int64(4), object(19)
memory usage: 378.2+ MB

### Converting data type

In [9]:
#Converting 'violation_date' to datetime
build['violation_date'] = pd.to_datetime(build['violation_date'])

In [10]:
#Adding 'month' colum and converting to .dt.month
build['month'] = build['violation_date'].dt.month

In [11]:
#Adding 'year' colum and converting to .dt.year datetime
build['year'] = build['violation_date'].dt.year

In [12]:
build.head()

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,street_direction,street_name,street_type,property_group,ssa,latitude,longitude,location,month,year
0,7149869,2024-04-16T14:21:39.000,2024-04-16,CN138106,OPEN,NaN,STOP/REMOVE NUISANCE,OTHER : :OTHER,REAR YARD - LARGE OVERGROWN DEAD TREE.,Remove and stop nuisance. (7-28-060),...,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024
1,7149868,2024-04-16T14:21:39.000,2024-04-16,CN067014,OPEN,NaN,REPAIR ROOF,OTHER : :OTHER,BUILDING / ROOF - ROTTING AND DETERIORATED SHI...,Failed to maintain roof in sound condition and...,...,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024
2,7149866,2024-04-16T14:21:39.000,2024-04-16,CN104015,OPEN,NaN,"REPLCE WINDOW PANES, PLEXGLAS",OTHER : :OTHER,NORTH ELEVATION / 2ND FLOOR WINDOW - BROKEN G...,"Replace broken, missing or defective window pa...",...,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024
3,7149865,2024-04-16T14:21:39.000,2024-04-16,CN079014,OPEN,NaN,REPAIR/REBUILD GARAGE OR SHED,OTHER : :OTHER,"WEST ELEVATION / 2 CAR FRAME GARAGE / ROOF, E...",Failed to maintain garage in sound condition a...,...,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024
4,7149867,2024-04-16T14:21:39.000,2024-04-16,CN070024,OPEN,NaN,REPAIR PORCH SYSTEM,OTHER : :OTHER,EAST ELEVATION / 1 STORY WOOD PORCH WITH ROOF ...,Failed to repair or replace defective or missi...,...,S,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024

In [13]:
#checking to make sure converting code is working
build.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1906801 entries, 0 to 1906800
Data columns (total 28 columns):
 #   Column                        Dtype
---  ------                        -----
 0   id                            int64
 1   violation_last_modified_date  object
 2   violation_date                datetime64[ns]
 3   violation_code                object
 4   violation_status              object
 5   violation_status_date         object
 6   violation_description         object
 7   violation_location            object
 8   violation_inspector_comments  object
 9   violation_ordinance           object
 10  inspector_id                  object
 11  inspection_number             int64
 12  inspection_status             object
 13  inspection_waived             object
 14  inspection_category           object
 15  department_bureau             object
 16  address                       object
 17  street_number                 int64
 18  street_direction              object
 19  street_name                   object
 20  street_type                   object
 21  property_group                int64
 22  ssa                           float64
 23  latitude                      float64
 24  longitude                     float64
 25  location                      object
 26  month                         int32
 27  year                          int32
dtypes: datetime64[ns](1), float64(3), int32(2), int64(4), object(18)
memory usage: 392.8+ MB

### Filtering For Heat Violations

In [14]:
#adding a column to identify heat violations with np where
build['is_heat'] = np.where(build['violation_description'] == 'HEAT UNIT ADEQUATELY', 'heat_violation', 'not_heat_violation')

In [15]:
#checking to see that the new column is added
build.columns

Index(['id', 'violation_last_modified_date', 'violation_date',
       'violation_code', 'violation_status', 'violation_status_date',
       'violation_description', 'violation_location',
       'violation_inspector_comments', 'violation_ordinance', 'inspector_id',
       'inspection_number', 'inspection_status', 'inspection_waived',
       'inspection_category', 'department_bureau', 'address', 'street_number',
       'street_direction', 'street_name', 'street_type', 'property_group',
       'ssa', 'latitude', 'longitude', 'location', 'month', 'year', 'is_heat'],
      dtype='object')

In [16]:
#checking the data frame to see the new column included
build.head()

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,street_name,street_type,property_group,ssa,latitude,longitude,location,month,year,is_heat
0,7149869,2024-04-16T14:21:39.000,2024-04-16,CN138106,OPEN,NaN,STOP/REMOVE NUISANCE,OTHER : :OTHER,REAR YARD - LARGE OVERGROWN DEAD TREE.,Remove and stop nuisance. (7-28-060),...,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation
1,7149868,2024-04-16T14:21:39.000,2024-04-16,CN067014,OPEN,NaN,REPAIR ROOF,OTHER : :OTHER,BUILDING / ROOF - ROTTING AND DETERIORATED SHI...,Failed to maintain roof in sound condition and...,...,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation
2,7149866,2024-04-16T14:21:39.000,2024-04-16,CN104015,OPEN,NaN,"REPLCE WINDOW PANES, PLEXGLAS",OTHER : :OTHER,NORTH ELEVATION / 2ND FLOOR WINDOW - BROKEN G...,"Replace broken, missing or defective window pa...",...,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation
3,7149865,2024-04-16T14:21:39.000,2024-04-16,CN079014,OPEN,NaN,REPAIR/REBUILD GARAGE OR SHED,OTHER : :OTHER,"WEST ELEVATION / 2 CAR FRAME GARAGE / ROOF, E...",Failed to maintain garage in sound condition a...,...,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation
4,7149867,2024-04-16T14:21:39.000,2024-04-16,CN070024,OPEN,NaN,REPAIR PORCH SYSTEM,OTHER : :OTHER,EAST ELEVATION / 1 STORY WOOD PORCH WITH ROOF ...,Failed to repair or replace defective or missi...,...,LA SALLE,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation

In [17]:
#using value counts to find the amount of heat violations to date
build['is_heat'].value_counts()

is_heat
not_heat_violation    1894133
heat_violation          12668
Name: count, dtype: int64

In [18]:
#combine month and year to fit the graph
build['month_year'] = build['month'].astype(str) + ' ' + '/' + ' ' +build['year'].astype(str)

In [19]:
#check the column is added
build.columns

Index(['id', 'violation_last_modified_date', 'violation_date',
       'violation_code', 'violation_status', 'violation_status_date',
       'violation_description', 'violation_location',
       'violation_inspector_comments', 'violation_ordinance', 'inspector_id',
       'inspection_number', 'inspection_status', 'inspection_waived',
       'inspection_category', 'department_bureau', 'address', 'street_number',
       'street_direction', 'street_name', 'street_type', 'property_group',
       'ssa', 'latitude', 'longitude', 'location', 'month', 'year', 'is_heat',
       'month_year'],
      dtype='object')

In [20]:
#check the data is tidy
build.head()

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,street_type,property_group,ssa,latitude,longitude,location,month,year,is_heat,month_year
0,7149869,2024-04-16T14:21:39.000,2024-04-16,CN138106,OPEN,NaN,STOP/REMOVE NUISANCE,OTHER : :OTHER,REAR YARD - LARGE OVERGROWN DEAD TREE.,Remove and stop nuisance. (7-28-060),...,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation,4 / 2024
1,7149868,2024-04-16T14:21:39.000,2024-04-16,CN067014,OPEN,NaN,REPAIR ROOF,OTHER : :OTHER,BUILDING / ROOF - ROTTING AND DETERIORATED SHI...,Failed to maintain roof in sound condition and...,...,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation,4 / 2024
2,7149866,2024-04-16T14:21:39.000,2024-04-16,CN104015,OPEN,NaN,"REPLCE WINDOW PANES, PLEXGLAS",OTHER : :OTHER,NORTH ELEVATION / 2ND FLOOR WINDOW - BROKEN G...,"Replace broken, missing or defective window pa...",...,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation,4 / 2024
3,7149865,2024-04-16T14:21:39.000,2024-04-16,CN079014,OPEN,NaN,REPAIR/REBUILD GARAGE OR SHED,OTHER : :OTHER,"WEST ELEVATION / 2 CAR FRAME GARAGE / ROOF, E...",Failed to maintain garage in sound condition a...,...,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation,4 / 2024
4,7149867,2024-04-16T14:21:39.000,2024-04-16,CN070024,OPEN,NaN,REPAIR PORCH SYSTEM,OTHER : :OTHER,EAST ELEVATION / 1 STORY WOOD PORCH WITH ROOF ...,Failed to repair or replace defective or missi...,...,ST,502551,NaN,41.703375,-87.627131,"\n, \n(41.70337489482741, -87.62713115963592)",4,2024,not_heat_violation,4 / 2024

###Stuff for Graph 1

In [50]:
no_heat = graph_no_heat[graph_no_heat['violation_code'] == 'CN132016']

In [51]:
no_heat.head()

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,street_type,property_group,ssa,latitude,longitude,location,month,year,is_heat,month_year
28,7148900,2024-04-15T09:05:32.000,2024-04-15,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:002 :,1263 S CENTRAL PARK APT 2 / ALL ROOMS 72F DEGR...,Heat dwelling unit adequately from September 1...,...,AVE,15707,NaN,41.864450,-87.715218,"\n, \n(41.864450173563014, -87.71521848941047)",4,2024,heat_violation,4 / 2024
634,7145591,2024-04-08T14:44:35.000,2024-04-08,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:002 :,2207 S / APT.2 / ALL ROOMS - 64F DEGREES; AT (...,Heat dwelling unit adequately from September 1...,...,AVE,26373,NaN,41.851364,-87.718497,"\n, \n(41.85136381385009, -87.71849743242603)",4,2024,heat_violation,4 / 2024
648,7146237,2024-04-08T13:05:35.000,2024-04-08,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,OTHER : :OTHER,CB132016 - 2ND FLOOR BEDROOMS TEMP WAS 66F AT ...,Heat dwelling unit adequately from September 1...,...,BLVD,397833,NaN,41.770705,-87.658975,"\n, \n(41.77070465111202, -87.65897462365271)",4,2024,heat_violation,4 / 2024
968,7144562,2024-04-04T13:10:34.000,2024-04-04,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:002 :,2ND FLOOR APT - ROOM TEMPERATURES WERE 62-64 D...,Heat dwelling unit adequately from September 1...,...,AVE,393366,NaN,41.771441,-87.610718,"\n, \n(41.77144133889547, -87.61071830476385)",4,2024,heat_violation,4 / 2024
971,7144544,2024-04-04T11:01:03.000,2024-04-04,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:001 :,APT. 7655-1ST FLOOR - ROOM TEMPERATURES WERE 4...,Heat dwelling unit adequately from September 1...,...,ST,423052,NaN,41.754399,-87.650055,"\n, \n(41.754399006032756, -87.65005481133355)",4,2024,heat_violation,4 / 2024

In [52]:
graph_no_heat = no_heat[no_heat['year'] >= 2019]

In [53]:
graph_no_heat.sort_values(by=['violation_date'], ascending=[True]).head(5)

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,street_type,property_group,ssa,latitude,longitude,location,month,year,is_heat,month_year
305508,6166958,2019-01-03T12:39:04.000,2019-01-03,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,OTHER : :BUILDING,APARTMENT 1E ROOM TEMPERATURE-60F.APARTMENT 1W...,Heat dwelling unit adequately from September 1...,...,ST,14701,NaN,41.877522,-87.749900,"\n, \n(41.87752204966017, -87.74989981615886)",1,2019,heat_violation,1 / 2019
305161,6167878,2019-02-22T15:01:28.000,2019-01-03,CN132016,COMPLIED,2019-02-22T00:00:00.000,HEAT UNIT ADEQUATELY,OTHER : :,APARTMENT #1- ROOM TEMPERATURE-LIVING ROOM 64F...,Heat dwelling unit adequately from September 1...,...,AVE,244386,NaN,41.992929,-87.674711,"\n, \n(41.992929183630224, -87.67471066293481)",1,2019,heat_violation,1 / 2019
305387,6207777,2019-03-11T09:34:40.000,2019-01-03,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,5648 S BISHOP 1 SENIOR DISABLED RESIDES IN AP...,ROOM TEERATURE IS 61-62 IN BEDROOM 1ST FLR APT...,Heat dwelling unit adequately from September 1...,...,ST,348008,NaN,41.790810,-87.661009,"\n, \n(41.79081017172071, -87.6610089537136)",1,2019,heat_violation,1 / 2019
305213,6167756,2019-01-03T16:11:14.000,2019-01-03,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,OTHER : :,1008 / APT. - 2 ROOM TEMPERATURES : LIVING ROO...,Heat dwelling unit adequately from September 1...,...,AVE,430704,51.0,41.749661,-87.600145,"\n, \n(41.74966135218435, -87.60014492429802)",1,2019,heat_violation,1 / 2019
305164,6167874,2019-02-22T15:00:19.000,2019-01-03,CN132016,COMPLIED,2019-02-19T00:00:00.000,HEAT UNIT ADEQUATELY,OTHER : :BL00876,APARTMENT #1- ROOM TEMPERATURE-LIVING ROOM 64F...,Heat dwelling unit adequately from September 1...,...,AVE,244386,NaN,41.992929,-87.674711,"\n, \n(41.992929183630224, -87.67471066293481)",1,2019,heat_violation,1 / 2019

In [54]:
no_heat.shape

(2273, 30)

In [61]:
no_heat['count'] = 1

In [62]:
no_heat.groupby(['month','year'])['violation_code'].head()

28        CN132016
634       CN132016
648       CN132016
968       CN132016
971       CN132016
            ...
298284    CN132016
298301    CN132016
298312    CN132016
298315    CN132016
298319    CN132016
Name: violation_code, Length: 224, dtype: object

In [65]:
no_heat[no_heat['violation_code'] == 'CN132016'].groupby('year')['count'].sum().sort_values(ascending=True)

year
2020    254
2023    263
2024    268
2021    406
2022    468
2019    614
Name: count, dtype: int64

In [66]:
no_heat[no_heat['violation_code'] == 'CN132016'].groupby('month')['count'].sum().sort_values(ascending=True)

month
6       1
7       1
8       1
9      12
5      34
4      75
3     152
10    228
12    320
11    351
2     417
1     681
Name: count, dtype: int64

In [82]:
no_heat.groupby(['year','month'])['violation_code'].count().reset_index().groupby(['year','month'])['violation_code'].sum()

year  month
2019  1        166
      2        113
      3         50
      4         21
      5         15
      7          1
      9          2
      10        66
      11       126
      12        54
2020  1         70
      2         41
      3         23
      9          3
      10        40
      11        33
      12        44
2021  1         25
      2        169
      3         25
      4         23
      5          9
      9          2
      10        38
      11        67
      12        48
2022  1        143
      2         37
      3         25
      4         17
      5          4
      6          1
      9          4
      10        45
      11        62
      12       130
2023  1         49
      2         45
      3         10
      4          5
      5          6
      8          1
      9          1
      10        39
      11        63
      12        44
2024  1        228
      2         12
      3         19
      4          9
Name: violation_code, dtype: int64

In [77]:
#good data for the graph
graph_one = no_heat.groupby(['year','month'])['violation_code'].count().reset_index().groupby(['year','month'])['violation_code'].sum().reset_index()

In [84]:
graph_one.shape

(50, 3)

In [86]:
graph_one.head(50)

    year  month  violation_code
0   2019      1             166
1   2019      2             113
2   2019      3              50
3   2019      4              21
4   2019      5              15
5   2019      7               1
6   2019      9               2
7   2019     10              66
8   2019     11             126
9   2019     12              54
10  2020      1              70
11  2020      2              41
12  2020      3              23
13  2020      9               3
14  2020     10              40
15  2020     11              33
16  2020     12              44
17  2021      1              25
18  2021      2             169
19  2021      3              25
20  2021      4              23
21  2021      5               9
22  2021      9               2
23  2021     10              38
24  2021     11              67
25  2021     12              48
26  2022      1             143
27  2022      2              37
28  2022      3              25
29  2022      4              17
30  2022      5               4
31  2022      6               1
32  2022      9               4
33  2022     10              45
34  2022     11              62
35  2022     12             130
36  2023      1              49
37  2023      2              45
38  2023      3              10
39  2023      4               5
40  2023      5               6
41  2023      8               1
42  2023      9               1
43  2023     10              39
44  2023     11              63
45  2023     12              44
46  2024      1             228
47  2024      2              12
48  2024      3              19
49  2024      4               9

In [81]:
#exporting data
graph_one.to_csv('graph_one_data.csv')