# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import requests
import geopandas as gpd

### More Chicagoans lacked heat in January than any month since 2019 amid historic cold

1. Go to the Chicago Data Portal: https://data.cityofchicago.org/
2. Find each dataset. Building violations, ward, and police.
3. Add a data notes section to your github readme. This should include information about the source of your data, where it came from, how often it is updated, and the period of data it contains (e.g. 2010-present or 2012 to 2019)
4. Lastly, test that this import works. This may take a while as the dataset is large.

In [71]:
build = pd.read_csv('https://data.cityofchicago.org/resource/22u3-xenr.csv?$limit=3000000')

In [72]:
# you can use any of these
ward = gpd.read_file('https://data.cityofchicago.org/api/geospatial/sp34-6z76?method=export&format=GeoJSON')
police = gpd.read_file('https://data.cityofchicago.org/api/geospatial/fthy-xz3r?method=export&format=GeoJSON')

In [73]:
# how a heat complaint is defined

In [74]:
build.head(3)

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,address,street_number,street_direction,street_name,street_type,property_group,ssa,latitude,longitude,location
0,7147204,2024-04-10T12:26:49.000,2024-04-10T00:00:00.000,CN063014,OPEN,NaN,CHIMNEY,EXTERIOR:S :,SOUTH FRONT CHIMNEY - ERODED MORTAR.,Failed to maintain chimney in safe and sound w...,...,1651 N FRANCISCO AVE,1651,N,FRANCISCO,AVE,75305,NaN,41.911727,-87.698982,"\n, \n(41.91172703733214, -87.69898221041089)"
1,7147305,2024-04-10T14:10:00.000,2024-04-10T00:00:00.000,CN079014,OPEN,NaN,REPAIR/REBUILD GARAGE OR SHED,OTHER : :OTHER,SOUTH ELEVATION / GARAGES - ROTTING WOOD OVERH...,Failed to maintain garage in sound condition a...,...,2525 E 106TH ST,2525,E,106TH,ST,501106,NaN,41.702664,-87.562080,"\n, \n(41.7026643321488, -87.56207970040357)"
2,7147295,2024-04-10T11:07:47.000,2024-04-10T00:00:00.000,CN062014,OPEN,NaN,PARAPET & COPING,OTHER : :OTHER,NORTH ELEVATION / PARAPET - WASHED OUT MORTAR....,Failed to maintain the parapet wall and coping...,...,7331 S RHODES AVE,7331,S,RHODES,AVE,405037,NaN,41.761186,-87.611382,"\n, \n(41.76118568407476, -87.6113822491066)"

In [75]:
build.shape

(1906071, 26)

In [76]:
build.columns

Index(['id', 'violation_last_modified_date', 'violation_date',
       'violation_code', 'violation_status', 'violation_status_date',
       'violation_description', 'violation_location',
       'violation_inspector_comments', 'violation_ordinance', 'inspector_id',
       'inspection_number', 'inspection_status', 'inspection_waived',
       'inspection_category', 'department_bureau', 'address', 'street_number',
       'street_direction', 'street_name', 'street_type', 'property_group',
       'ssa', 'latitude', 'longitude', 'location'],
      dtype='object')

In [77]:
ward.columns

Index(['shape_area', 'shape_leng', 'ward', 'geometry'], dtype='object')

In [78]:
police.columns

Index(['dist_label', 'dist_num', 'geometry'], dtype='object')

In [81]:
build_heat = build[build['violation_description'] == 'HEAT UNIT ADEQUATELY']

In [84]:
build_heat

,id,violation_last_modified_date,violation_date,violation_code,violation_status,violation_status_date,violation_description,violation_location,violation_inspector_comments,violation_ordinance,...,address,street_number,street_direction,street_name,street_type,property_group,ssa,latitude,longitude,location
143,7145591,2024-04-08T14:44:35.000,2024-04-08T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:002 :,2207 S / APT.2 / ALL ROOMS - 64F DEGREES; AT (...,Heat dwelling unit adequately from September 1...,...,2207 S RIDGEWAY AVE,2207,S,RIDGEWAY,AVE,26373,NaN,41.851364,-87.718497,"\n, \n(41.85136381385009, -87.71849743242603)"
194,7146237,2024-04-08T13:05:35.000,2024-04-08T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,OTHER : :OTHER,CB132016 - 2ND FLOOR BEDROOMS TEMP WAS 66F AT ...,Heat dwelling unit adequately from September 1...,...,6753 S LOOMIS BLVD,6753,S,LOOMIS,BLVD,397833,NaN,41.770705,-87.658975,"\n, \n(41.77070465111202, -87.65897462365271)"
413,7144175,2024-04-04T13:01:43.000,2024-04-04T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,OTHER : :OTHER,UNIT 104 / ROOM TEMPERATURES : BEDROOM AT FRON...,Heat dwelling unit adequately from September 1...,...,5748 S BLACKSTONE AVE,5748,S,BLACKSTONE,AVE,19107,NaN,41.790078,-87.590369,"\n, \n(41.79007818420464, -87.59036862158871)"
426,7144562,2024-04-04T13:10:34.000,2024-04-04T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:002 :,2ND FLOOR APT - ROOM TEMPERATURES WERE 62-64 D...,Heat dwelling unit adequately from September 1...,...,6754 S ST LAWRENCE AVE,6754,S,ST LAWRENCE,AVE,393366,NaN,41.771441,-87.610718,"\n, \n(41.77144133889547, -87.61071830476385)"
512,7144544,2024-04-04T11:01:03.000,2024-04-04T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,INTERIOR:001 :,APT. 7655-1ST FLOOR - ROOM TEMPERATURES WERE 4...,Heat dwelling unit adequately from September 1...,...,7655 S CARPENTER ST,7655,S,CARPENTER,ST,423052,NaN,41.754399,-87.650055,"\n, \n(41.754399006032756, -87.65005481133355)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1904276,1222560,2006-01-11T13:32:16.000,2006-01-03T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,NaN,2 BEDROOMS 58 DEGREES,Heat dwelling unit adequately from September 1...,...,3430 W FRANKLIN BLVD,3430,W,FRANKLIN,BLVD,553306,NaN,41.890113,-87.712533,"\n, \n(41.89011343452869, -87.71253255596612)"
1904281,1220412,2006-01-10T14:21:31.000,2006-01-03T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,NaN,6239 2ND FLOOR,Heat dwelling unit adequately from September 1...,...,6237 N CLARK ST,6237,N,CLARK,ST,218578,NaN,41.995428,-87.670041,"\n, \n(41.99542843435551, -87.6700410393691)"
1904329,1213392,2006-01-09T11:08:06.000,2006-01-03T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,NaN,INSUFFICIENT HEAT IN UNIT 5235-1-63 DEGREES 52...,Heat dwelling unit adequately from September 1...,...,5235 S DREXEL AVE,5235,S,DREXEL,AVE,18670,NaN,41.799725,-87.603779,"\n, \n(41.79972461723391, -87.60377904890957)"
1904343,1214651,2006-01-09T16:01:33.000,2006-01-03T00:00:00.000,CN132016,OPEN,NaN,HEAT UNIT ADEQUATELY,NaN,NO HEAT COMMON PLANT 1624 2W 64.9 DEGREES 1624...,Heat dwelling unit adequately from September 1...,...,1620 W 79TH ST,1620,W,79TH,ST,20828,32.0,41.750453,-87.664340,"\n, \n(41.75045254297277, -87.66433988764588)"
1904709,1709812,2007-03-22T10:58:50.000,2006-01-02T00:00:00.000,CN132016,COMPLIED,2007-03-21T00:00:00.000,HEAT UNIT ADEQUATELY,NaN,ENTIRE BUILDING TURN HEAT ON THROUGHOUT BUILDING,Heat dwelling unit adequately from September 1...,...,820 E HYDE PARK BLVD,820,E,HYDE PARK,BLVD,18420,47.0,41.802379,-87.605473,"\n, \n(41.802379299308605, -87.6054727458616)"

In [86]:
print(build_heat)

              id violation_last_modified_date           violation_date  \
143      7145591      2024-04-08T14:44:35.000  2024-04-08T00:00:00.000
194      7146237      2024-04-08T13:05:35.000  2024-04-08T00:00:00.000
413      7144175      2024-04-04T13:01:43.000  2024-04-04T00:00:00.000
426      7144562      2024-04-04T13:10:34.000  2024-04-04T00:00:00.000
512      7144544      2024-04-04T11:01:03.000  2024-04-04T00:00:00.000
...          ...                          ...                      ...
1904276  1222560      2006-01-11T13:32:16.000  2006-01-03T00:00:00.000
1904281  1220412      2006-01-10T14:21:31.000  2006-01-03T00:00:00.000
1904329  1213392      2006-01-09T11:08:06.000  2006-01-03T00:00:00.000
1904343  1214651      2006-01-09T16:01:33.000  2006-01-03T00:00:00.000
1904709  1709812      2007-03-22T10:58:50.000  2006-01-02T00:00:00.000

        violation_code violation_status    violation_status_date  \
143           CN132016             OPEN                      NaN
194           CN132016             OPEN                      NaN
413           CN132016             OPEN                      NaN
426           CN132016             OPEN                      NaN
512           CN132016             OPEN                      NaN
...                ...              ...                      ...
1904276       CN132016             OPEN                      NaN
1904281       CN132016             OPEN                      NaN
1904329       CN132016             OPEN                      NaN
1904343       CN132016             OPEN                      NaN
1904709       CN132016         COMPLIED  2007-03-21T00:00:00.000

        violation_description   violation_location  \
143      HEAT UNIT ADEQUATELY       INTERIOR:002 :
194      HEAT UNIT ADEQUATELY  OTHER   :    :OTHER
413      HEAT UNIT ADEQUATELY  OTHER   :    :OTHER
426      HEAT UNIT ADEQUATELY       INTERIOR:002 :
512      HEAT UNIT ADEQUATELY       INTERIOR:001 :
...                       ...                  ...
1904276  HEAT UNIT ADEQUATELY                  NaN
1904281  HEAT UNIT ADEQUATELY                  NaN
1904329  HEAT UNIT ADEQUATELY                  NaN
1904343  HEAT UNIT ADEQUATELY                  NaN
1904709  HEAT UNIT ADEQUATELY                  NaN

                              violation_inspector_comments  \
143      2207 S / APT.2 / ALL ROOMS - 64F DEGREES; AT (...
194      CB132016 - 2ND FLOOR BEDROOMS TEMP WAS 66F AT ...
413      UNIT 104 / ROOM TEMPERATURES : BEDROOM AT FRON...
426      2ND FLOOR APT - ROOM TEMPERATURES WERE 62-64 D...
512      APT. 7655-1ST FLOOR - ROOM TEMPERATURES WERE 4...
...                                                    ...
1904276                              2 BEDROOMS 58 DEGREES
1904281                                     6239 2ND FLOOR
1904329  INSUFFICIENT HEAT IN UNIT 5235-1-63 DEGREES 52...
1904343  NO HEAT COMMON PLANT 1624 2W 64.9 DEGREES 1624...
1904709   ENTIRE BUILDING TURN HEAT ON THROUGHOUT BUILDING

                                       violation_ordinance  ...  \
143      Heat dwelling unit adequately from September 1...  ...
194      Heat dwelling unit adequately from September 1...  ...
413      Heat dwelling unit adequately from September 1...  ...
426      Heat dwelling unit adequately from September 1...  ...
512      Heat dwelling unit adequately from September 1...  ...
...                                                    ...  ...
1904276  Heat dwelling unit adequately from September 1...  ...
1904281  Heat dwelling unit adequately from September 1...  ...
1904329  Heat dwelling unit adequately from September 1...  ...
1904343  Heat dwelling unit adequately from September 1...  ...
1904709  Heat dwelling unit adequately from September 1...  ...

                        address  street_number street_direction  street_name  \
143         2207 S RIDGEWAY AVE           2207                S     RIDGEWAY
194          6753 S LOOMIS BLVD           6753                S       LOOMIS
413       5748 S BLACKSTONE AVE           5748                S   BLACKSTONE
426      6754 S ST LAWRENCE AVE           6754                S  ST LAWRENCE
512         7655 S CARPENTER ST           7655                S    CARPENTER
...                         ...            ...              ...          ...
1904276    3430 W FRANKLIN BLVD           3430                W     FRANKLIN
1904281         6237 N CLARK ST           6237                N        CLARK
1904329       5235 S DREXEL AVE           5235                S       DREXEL
1904343          1620 W 79TH ST           1620                W         79TH
1904709    820 E HYDE PARK BLVD            820                E    HYDE PARK

        street_type property_group   ssa   latitude  longitude  \
143             AVE          26373   NaN  41.851364 -87.718497
194            BLVD         397833   NaN  41.770705 -87.658975
413             AVE          19107   NaN  41.790078 -87.590369
426             AVE         393366   NaN  41.771441 -87.610718
512              ST         423052   NaN  41.754399 -87.650055
...             ...            ...   ...        ...        ...
1904276        BLVD         553306   NaN  41.890113 -87.712533
1904281          ST         218578   NaN  41.995428 -87.670041
1904329         AVE          18670   NaN  41.799725 -87.603779
1904343          ST          20828  32.0  41.750453 -87.664340
1904709        BLVD          18420  47.0  41.802379 -87.605473

                                                location
143       \n,  \n(41.85136381385009, -87.71849743242603)
194       \n,  \n(41.77070465111202, -87.65897462365271)
413       \n,  \n(41.79007818420464, -87.59036862158871)
426       \n,  \n(41.77144133889547, -87.61071830476385)
512      \n,  \n(41.754399006032756, -87.65005481133355)
...                                                  ...
1904276   \n,  \n(41.89011343452869, -87.71253255596612)
1904281    \n,  \n(41.99542843435551, -87.6700410393691)
1904329   \n,  \n(41.79972461723391, -87.60377904890957)
1904343   \n,  \n(41.75045254297277, -87.66433988764588)
1904709   \n,  \n(41.802379299308605, -87.6054727458616)

[12668 rows x 26 columns]